spring:
  application:
    name: demo-secrets-config-client
  config:
    import:
     - "optional:configserver:"
     # - "optional:configtree:./secret-config-root/"
  cloud:
    config:
      uri: http://localhost:8888
      # ./secret-config-root/spring/cloud/config/password
#      password: ${my-config-base.passWord} # DOES NOT WORK because casing seems to be broken in bootstrap context binder
      password: ${my-config-base.pass-word}

my-config-base:
  url: example.com
  passWord: dummy-password-needed
  another-value: dummy-password-needed

another-config:
  value1: ${my-config-base.pass-word}
  value2: ${my-config-base.another-value}
  value3: ${my-config-base.passWord}
  value4: ${my-config-base.anotherValue} # DOES NOT WORK because casing seems to be broken in binder
  # logs LOOK HERE AT THIS config: AnotherConfig(value1=dummy-password-needed, value2=dummy-password-needed, value3=dummy-password-needed, value4=${my-config-base.anotherValue})

server:
  port: 9333

