spring:
  application:
    name: demo-secrets-config-client
  config:
    import:
     - "configserver:"
     - "optional:configtree:./secret-config-root/"
  cloud:
    config:
      uri: http://localhost:8888
      password: # ./secret-config-root/spring/cloud/config/password

server:
  port: 9333

